# Introduction to Numpy Arrays

<p style="font-size:20px">In this Notebook we are going to learn about the most important library in python for Data Science used for the mathematical computational tasks and i am pretty sure you know the name which is NumPy</p>

# Why Numpy if arrays and lists are available in python
  NumPy arrays are implemented in C and optimized for performance. They are more memory-efficient and faster for numerical computations compared to Python lists. They also provide us function to efficiently performs operations on our arrays. There are many advanteges that numpy provides over python arrays you can check out there :
<p style="font-size:20px"><a href="https://medium.com/@munnebsheikh10/why-use-numpy-arrays-instead-of-python-inbuilt-lists-9b0b34124968">Why Numpy</a></p>

In [2]:
# First we are going to import numpy 
import numpy as np

# NdArray in numpy
<p style="font-size:20px"> 
The array object in NumPy is called ndarray meaning 'n-dimensional array'. To begin with, you will use one of the most common array types: the one-dimensional array ('1-D'). A 1-D array represents a standard list of values entirely in one dimension. Remember that in NumPy, all of the elements within the array are of the same type
</p>

In [3]:
# We have defined the 1-D array with 4 values and then we printed it
one_dimensional_array=np.array([1,2,3,4])
print(one_dimensional_array)

[1 2 3 4]


In [8]:
"""
Defining numpy array by defining size we defined the npArray of size 6.
Values are bydefault start from 0 and go till given_size-1 (as given_size=6)
"""
array_by_size=np.arange(6)
print(array_by_size)

[0 1 2 3 4 5]


In [9]:
# Create an array that starts from the integer 1, ends at 20, incremented by 3.
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


<p style="font-size:20px">
What if you wanted to create an array with five evenly spaced values in the interval from 0 to 100? As you may notice below, you have 3 parameters that a function must take. One paremeter is the starting number, in  this case 0, the final number 100 and the number of elements in the array, in this case, 5. NumPy has a function that allows you to do specifically this by using `np.linspace()`.
</p>

In [11]:
lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


<p style="font-size:20px">
Did you notice above that the output of the function is presented in the float value form (e.g. "... 25. 50. ...")? The reason is that the default type for values in the NumPy function `np.linspace` is a floating point (`np.float64`). You can easily specify your data type using `dtype`. If you access the built-in documentation of the functions, you may notice that most functions take in an optional parameter `dtype`. In addition to float, NumPy has several other data types such as int, and char.
To change the type to integers, you need to set the dtype to `int`. You can do so, even in the previous functions. Feel free to try it out and modify the cells to output your desired data type. 
</p>

In [14]:
# using dType in linespace python function
lin_spaced_arr_int = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr_int)

[  0  25  50  75 100]


In [13]:
# Using dType in arange python function
c_int = np.arange(1, 20, 3, dtype=int)
print(c_int)

[ 1  4  7 10 13 16 19]


In [16]:
# Checking the type of the array
char_arr = np.array(['Welcome to Math for PY!'])
print(char_arr)
print(char_arr.dtype) # Prints the data type of the array

['Welcome to Math for PY!']
<U23



Did you notice above that the output of the data type of the `char_arr` array is `<U23`? 
This means that the string (`'Welcome to Math for ML!'`) is a 23-character (23) unicode string (`U`) on a little-endian architecture (`<`). You can learn more about data types [here](https://numpy.org/doc/stable/user/basics.types.html).


# More on Numpys arrays
One of the advantages of using NumPy is that you can easily create arrays with built-in functions such as: 
- `np.ones()` - Returns a new array setting values to one.
- `np.zeros()` - Returns a new array setting values to zero.
- `np.empty()` - Returns a new uninitialized array. 
- `np.random.rand()` - Returns a new array with values chosen at random.

In [17]:
# Return a new array of shape 3, filled with ones. 
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [18]:
# Return a new array of shape 3, filled with zeroes.
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [19]:
# Return a new array of shape 3, without initializing entries.
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


<a name='2'></a>
# 2 - Multidimensional Arrays #
With NumPy you can also create arrays with more than one dimension. In the above examples, you dealt with 1-D arrays, where you can access their elements using a single index. A multidimensional array has more than one column. Think of a multidimensional array as an excel sheet where each row/column represents a dimension.

![0_Vh-pKXTJsdL-9FT0.png](https://th.bing.com/th/id/OIP.j_XesavgC-AzEk__okA1SgHaD6?pid=ImgDet&rs=1)

In [20]:
# Create a 2 dimensional array (2-D)
two_dim_arr = np.array([[1,2,3], [4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


An alternative way to create a multidimensional array is by reshaping the initial 1-D array. Using `np.reshape()` you can rearrange elements of the previous array into a new shape. 

In [27]:
# 1-D array 
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# Multidimensional array using reshape()
multi_dim_arr = np.reshape(
                one_dim_arr, # the array to be reshaped
               (2,3) # dimensions of the new array
              )
# Print the new 2-D array with two rows and three columns
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


## 2.1 - Finding size, shape and dimension. ##

How to find the size, dimension and shape of an array. These are all atrributes of a `ndarray` and can be accessed as follows:
- `ndarray.ndim` - Stores the number dimensions of the array. 
- `ndarray.shape` - Stores the shape of the array. Each number in the tuple denotes the lengths of each corresponding dimension.
- `ndarray.size` - Stores the number of elements in the array.

In [28]:
# Dimension of the 2-D array multi_dim_arr e.g (2D,3D,4D, etc)
multi_dim_arr.ndim

2

In [30]:
# Shape of the 2-D array multi_dim_arr 
# For 2D we can name as rows and column but it is not possible to name in 3D or
# more so it is good to define in a wa like x,y,z or x1,x2,x3,--,xn
# e.g(2 in x - 3 in y , 2 in x - 3 in y - 4 in z ,etc )
# Returns shape of 2 rows and 3 columns

multi_dim_arr.shape

(2, 3)

In [32]:
# Size of the array multi_dim_arr
# Returns total number of elements
multi_dim_arr.size

6


#  Array math operations #
In this section, you will see that NumPy allows you to quickly perform elementwise addition, substraction, multiplication and division for both 1-D and multidimensional arrays. The operations are performed using the math symbol for each '+', '-' and '*'. *Recall that addition of Python lists works completely differently as it would append the lists, thus making a longer list, in addition, subtraction and multiplication of Python lists do not work*. 

In [33]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


<a name='3-1'></a>
## Multiplying vector(1D array) with a scalar (broadcasting) ##
Suppose you need to convert miles to kilometers. To do so, you can use the NumPy array functions that you've learned so far. You can do this by carrying out an operation between an array (miles) and a single number (the conversion rate which is a scalar). Since, 1 mile = 1.6 km, NumPy computes each multiplication within each cell. 

This concept is called **broadcasting**, which allows you to perform operations specifically on arrays of different shapes. 

In [37]:
vector = np.array([[2,1],[1,2]])
vector * 2

array([[4, 2],
       [2, 4]])

![Image](https://upscfever.com/upsc-fever/en/programming/datascience/images/NumTwoDb.png)

#  - Indexing and slicing #
Indexing is very useful as it allows you to select specific elements from an array. It also lets you select entire rows/columns or planes as you'll see in future assignments for multidimensional arrays. 

## - Indexing ##
Let us select specific elements from the arrays as given.

In [40]:
# Select the third element of the array. Remember the counting starts from 0.
a = ([1, 2, 3, 4, 5])
print(a[2])

# Select the first element of the array.
print(a[0])

3
1


For multidimensional arrays of shape `n`, to index a specific element, you must input `n` indices, one for each dimension.

In [43]:
# Indexing on a 2-D array
two_dim = np.array((
          [1, 2, 3],
          [4, 5, 6], 
          [7, 8, 9]))

# Select element number 8 from the 2-D array using indices i, j.
print(two_dim[2][1])

8


##  - Slicing ##
Slicing gives you a sublist of elements that you specify from the array. The slice notation specifies a start and end value, and copies the list from start up to but not including the end (end-exclusive). 

The syntax is:

`array[start:end:step]`

If no value is passed to start, it is assumed `start = 0`, if no value is passed to end, it is assumed that `end = length of array - 1` and if no value is passed to step, it is assumed `step = 1`.

# **a = ([1, 2, 3, 4, 5])** 
a is defined before while indexing

In [51]:
# Slice the array a to get the array [2,3,4] by giving starting and ending 
# slicing point 
sliced_arr = a[1:4]
print(sliced_arr)

[2, 3, 4]


In [45]:
# Slice the array a to get the array [1,2,3] by giving just the end point
# and start point is by default 0
sliced_arr = a[:3]
print(sliced_arr)

[1, 2, 3]


In [48]:
# Slice the array a to get the array [3,4,5] by giving the starting point and 
# by default the end point is size
sliced_arr = a[2:]
print(sliced_arr)

[3, 4, 5]


In [55]:
# we also have a :: operator which is used to do more advance slicing
# a[start:end:steps] you can leave some args if you want suppose i leave `end` 
# and `steps` i will write like a[start::] or if i leave `end` then i will write 
# a[start::end] i hope you get it
sliced_arr=a[0:5:3]
print(sliced_arr)

[1, 4]


In [56]:
# Note that a == a[:] == a[::] do some brainstorming on this why
print(a == a[:] == a[::])

True


In [57]:
# Slice the two_dim array to get the first two rows
sliced_arr_1 = two_dim[0:2]
sliced_arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
# Similarily, slice the two_dim array to get the last two rows
sliced_two_dim_rows = two_dim[1:3]
print(sliced_two_dim_rows)

[[4 5 6]
 [7 8 9]]


In [65]:
# Sliced the column , is representing that we want to slice column
sliced_two_dim_cols = two_dim[:,0]
print(sliced_two_dim_cols)

[1 4 7]


# - Stacking #
Finally, stacking is a feature of NumPy that leads to increased customization of arrays. It means to join two or more arrays, either horizontally or vertically, meaning that it is done along a new axis. 

- `np.vstack()` - stacks vertically
- `np.hstack()` - stacks horizontally
- `np.hsplit()` - splits an array into several smaller arrays

In [66]:
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [67]:
# Stack the arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [68]:
# Stack the arrays horizontally
horz_stack = np.hstack((a1, a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]


## Exercises ##
Well done! Now, from what you learned today, try to answer the following question. 

### Question 1 ###
Is there a difference between `np.zeros()` and `np.empty()`? Select one of the options given:
- A. No difference, they both output arrays of zeros. 
- B. `np.zeros()` is not initialized, but gives an output of zeros. 
- C. `np.zeros()` is faster to execute than `np.empty()`.
- D. `np.empty()` outputs an uninitialized array, but `np.zeros()` outputs an initialized array of value zero.

# Congratulations on finishing your Notebook for learning Numpy